test: &default

  # Credentials for REST APIs
  client_id: ASpzjFV-Q1QC0SwpbCm3VPGu2zLMiTjpsf2QZbjpkID-rdrVEPxkhge4nF7uNgoarIz4Z-gZyKUEtVr2
  client_secret: EOiisJPKHL9RKMqJQANr3KZG_o-k0p_o5sfrzQbLMMj6YSu8UTjTbZq6NU0jMyYknyzN0VO2f7_-DA0V

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: xxxx #APP-80W284485P519543T
  username: sb-ujbtd491592_api1.business.example.com
  password: NAHVYVFJLCE6EHFC
  signature: AavbZkoAYDuwT03Xa07tZC.e5culApeDwUAQoUa4QmvTZVLA4OLEdK0Y

  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: Platform.sdk.seller@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  # mode: live
